Clear the bss section before calling C codes
rtfb/riscv64-in-qemu pull request #42
Opened 2021-11-03 12:29 UTC by RinHizakura

Thank you for the great project at first!

I have a question here: For the .bss section, as far as I know, it will contain the area of memory used to hold static variables which must be initialized to zero. Although it may not be a big problem on the emulator(since the emulator could initialize the memory region to zero itself), I think it is still worth fixing it. Do we need to ensure the correctness by clearing the .bss section before ever calling any C codes? Or am I misunderstanding something for the question?

2021-12-01 19:39 UTC, rtfb commented
Hi, first of all, I'm very sorry it took me so long to reply, and second, thanks a lot for your contribution!

You're right, the .bss section should be zeroed out. This will only affect the kernel code, which may end up not depending on it, but it's certainly the right thing to do. There's a minor problem with the implementation, I will comment inline.

2021-12-01 19:46 UTC, rtfb requested changes

2021-12-01 19:46 UTC, rtfb commented on src/boot.s
> +        sd      zero, (a0)
There's a subtle (and obscure, on our side) problem here: we build both 64- and 32-bit targets, so using `sd` instruction directly fails to build for 32 bits:

```
$ make all
[...]
riscv64-linux-gnu-gcc -march=rv32g -mabi=ilp32 -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -ffreestanding -Tsrc/baremetal.ld -Iinclude \
	-Wl,--defsym,ROM_START=0x20400000 -Wa,--defsym,UART=0x10013000 \
	-Wa,--defsym,XLEN=32 \
	src/baremetal-fib.s src/baremetal-print.s src/baremetal-poweroff.s -o out/test_sifive_e32
riscv64-linux-gnu-gcc -march=rv32g -mabi=ilp32 -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -ffreestanding -Tsrc/baremetal.ld -Iinclude \
	-Wl,--defsym,ROM_START=0x20400000 -Wa,--defsym,UART=0x10013000 \
	-Wa,--defsym,XLEN=32 \
	src/boot.s src/baremetal-print.s src/baremetal-poweroff.s src/userland.c src/kernel.c src/syscalls.c src/pmp.c src/riscv.c src/fdt.c src/string.c src/proc_test.c -o out/user_sifive_e32
src/boot.s: Assembler messages:
src/boot.s:41: Error: unrecognized opcode `sd zero,(a0)'
Makefile:163: recipe for target 'out/user_sifive_e32' failed
make: *** [out/user_sifive_e32] Error 1
```

We have a macro `sx` defined for that [here](https://github.com/rtfb/riscv64-in-qemu/blob/master/src/machine-word.inc#L25-L27). You can find a usage example [here](https://github.com/rtfb/riscv64-in-qemu/blob/master/src/boot.s#L138).

(And I wonder why github actions didn't catch this... This is something I'll have to look into).

2021-12-01 20:06 UTC, rtfb commented on src/boot.s
> +        sd      zero, (a0)
Okay, looks like this is the reason why github actions didn't run: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

#TIL

2021-12-04 02:00 UTC, RinHizakura commented
Thank for reviewing!

To solve the problem of  `sd` instruction, I think using your macro `sx` directly here is not the solution. Since our purpose is to clean up a fixed size memory space, the key point between 32 and 64 bits should be the shift offset of address (which means the second instruction after `clean_bss_loop` label: `addi`). 

A simple solution for this could be using `sw` and 4 bytes shifting for both 32 and 64 bits targets. It is a general solution. The only  concern for this is that we actually have the potential to optimize this for 64 bits target(by `sd` + 8 bytes shifting).

2021-12-06 07:04 UTC, rtfb commented
> To solve the problem of `sd` instruction, I think using your macro `sx` directly here is not the solution. Since our purpose is to clean up a fixed size memory space, the key point between 32 and 64 bits should be the shift offset of address (which means the second instruction after `clean_bss_loop` label: `addi`).

There is a constant, [REGBYTES](https://github.com/rtfb/riscv64-in-qemu/blob/master/src/machine-word.inc#L10) that's defined to be either 4 or 8, depending on the target. It could be used to advance the pointer accordingly.

But using `sw` unconditionally seems like a perfectly valid solution to me, so I'm merging this in.

Thanks again for your contribution!

2021-12-06 07:05 UTC, rtfb approved these changes

2021-12-06 07:06 UTC, merged